### ISSUE TITLE
pip install fails because of missing files

### ISSUE THREAD

**Issue by gorilych** [ingrammicro/apsconnect-cli#45]
```
# pip install apsconnectcli
Collecting apsconnectcli
  Using cached apsconnectcli-1.7.23.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b9jTvA/apsconnectcli/setup.py", line 14, in <module>
        with open(join(here, 'VERSION')) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-b9jTvA/apsconnectcli/VERSION'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b9jTvA/apsconnectcli/
```

**Comment by hayorov** [comment]
Dear @gorilych thank you for the issue and your feedback.

Fixed in  #46 https://github.com/ingrammicro/apsconnect-cli/releases/tag/v1.7.24
